# Generated by Django 5.0 on 2024-08-03 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=800)),
                ('category', models.CharField(choices=[('Mental-Health', 'Mental-Health'), ('Heart-Decease', 'Heart-Decease'), ('Covid-19', 'Covid-19'), ('Immunization', 'Immunization')], max_length=50)),
                ('summary', models.TextField()),
                ('content', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
