# Generated by Django 5.0 on 2024-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
