# Generated by Django 5.0 on 2024-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_additionalinfomodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfomodel',
            name='profile_picture',
            field=models.URLField(max_length=800),
        ),
    ]
